### ISSUE TITLE
MongoDB failure on app that doesn't use Mongo

### ISSUE THREAD

**Issue by chrismclennon** [Pythagora-io/pythagora#5]
Hey Pythagora. I love what you're aiming for with the project. I have a simple Express app that runs on a postgresql backend, and I created Pythagora tests on a few simple paths. When I went to run them, I encountered a Mongo error I wasn't expecting:

```
Running tests in 3 seconds...
Listening on port 5001
Starting tests on endpoints:
/
/v1/status

(node:9065) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
The app has crashed!
This is likely not related to Pythagora, but the app itself.
MongoRuntimeError: Unable to parse undefined:undefined with URL
    at new HostAddress (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/utils.js:888:34)
    at fromString (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/utils.js:930:16)
    ... 4 lines matching cause stack trace ...
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/chris/Workspace/my-project/node_modules/mongoose/lib/connection.js:799:19)
    at /Users/chris/Workspace/my-project/node_modules/mongoose/lib/index.js:409:10
    at /Users/chris/Workspace/my-project/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5 {
  cause: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:372:5)
      at URL.onParseError (node:internal/url:553:9)
      at new URL (node:internal/url:629:5)
      at new HostAddress (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/utils.js:885:19)
      at fromString (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/utils.js:930:16)
      at Array.map (<anonymous>)
      at parseOptions (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/connection_string.js:210:45)
      at new MongoClient (/Users/chris/Workspace/my-project/node_modules/mongodb/lib/mongo_client.js:46:63)
      at /Users/chris/Workspace/my-project/node_modules/mongoose/lib/connection.js:802:16
      at new Promise (<anonymous>) {
    input: 'iLoveJS://undefined:undefined',
    code: 'ERR_INVALID_URL'
  },
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by LeonOstrez** [comment]
Hi @chrismclennon ! Thank you so much for trying out Pythagora, really appreciate it.

Looking at this trace I can’t really tell what happened and where the issue is. It looks like you are using mongoose (since you have it in node_modules) but you also mentioned you have postgresql. How come you are using both? From trace it seems like you are trying to connect with mongoose but you are sending 'ilovejs://undefined:undefined' as URL.

In general it is ok to use Pythagora with project that doesn’t have mongoose and it should all run without crashing. Issue on projects without mongoose is that Pythagora will not be able to capture database queries so endpoints that do interact with postgresql will probably fail in testing phase until we start supporting postgresql. We are still not sure at what point we will support it but we have it planned for future.
