### ISSUE TITLE
Got an error trying to create a project. 'Project' object has no attribute 'is_complex_app'

### ISSUE THREAD

**Issue by keyvez** [Pythagora-io/pythagora#74]
---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):

  File "/Users/gaurav/Documents/Code/ai/gpt-pilot/pilot/main.py", line 126, in <module>
    started = project.start()

  File "/Users/gaurav/Documents/Code/ai/gpt-pilot/pilot/helpers/Project.py", line 217, in start
    self.tech_lead.create_development_plan()

  File "/Users/gaurav/Documents/Code/ai/gpt-pilot/pilot/helpers/agents/TechLead.py", line 57, in create_development_plan
    "is_complex_app": self.project.is_complex_app,

AttributeError: 'Project' object has no attribute 'is_complex_app'

**Comment by TMCTG** [comment]
A workaround is removing the line:
`                    "is_complex_app": self.project.is_complex_app,`
from gpt-pilot-main/pilot/helpers/agents/TechLead.py
Not sure if this will cause other issues down the road.
